#!/usr/bin/env python
# -*- python -*-
from __future__ import division

__version__ = "$Revision: 1.3 $"

"""
textsum: DESCRIPTION
"""

import sys
import textinput

def textsum(*args):
    for textfilename, textfile in textinput.files():
        ints = map(int, infile)
        print sum(ints)/len(ints)

def parse_options(args):
    from optparse import OptionParser

    global options
    
    usage = "%prog [OPTION]..."
    version = "%%prog %s" % __version__
    parser = OptionParser(usage=usage, version=version)
    
    options, args = parser.parse_args(args)

    return args

def main(args):
    args = parse_options(args)

    return textsum(*args)

def _test(*args, **kwargs):
    import doctest
    doctest.testmod(sys.modules[__name__], *args, **kwargs)

if __name__ == "__main__":
    if __debug__:
        _test()
    sys.exit(main(sys.argv[1:]))
